### ISSUE TITLE
La utilidad TemplateUtils debe realizar un "escape" del pattern elegido "{}"

### ISSUE THREAD

**Issue by bsandoval** [jokoframework/joko-utils#5]
@Test
El siguiente test muestra que si utilizo llaves "{}" dentro del template que deseo mapear, resultan algunos errores.

```
public void testEscapeStr() {
    String name = "Bea";
    Integer puntos = 800;

    String template = "Hola name tu tienes { puntos } puntos acumulados";
    String expectedValue = "Hola "+name+" tu tienes { "+puntos+" } puntos acumulados";

    Map<String, Object> values = new HashMap<String, Object>();
    values.put("name", name);
    values.put("puntos", puntos);
    String value = TemplateUtils.formatMap(template, values);
    Assert.assertEquals(expectedValue, value);
}
```

Tests in error: 
  testEscapeStr(io.github.jokoframework.template.TemplateUtilTest): Unmatched braces in the pattern.

Y para este caso: String template = "Hola name tu tienes { puntos puntos acumulados";

Tests in error: 
  testEscapeStr(io.github.jokoframework.template.TemplateUtilTest): can't parse argument number:

**Comment by roskoff** [comment]
En #7 se puede entender mejor como se comporta la clase. El template tiene seguir los mismos delineamientos que MessageFormat, para escapar una llave tiene que ir entre comillas simples.
